version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      datatables-packages:
        patterns:
          - 'datatables.net*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
