AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config.ru
  Include:
    - config/routes.rb
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - lib/tasks/import/**/*
    - spec/**/*

Style/Documentation:
  Enabled: false
