require:
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - config/{environments,initializers}/**/*
    - config/{application,boot,environment,puma,spring}.rb
    - db/schema.rb
    - db/migrate/*.rb
    - config.ru
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - lib/tasks/import/**/*
    - spec/**/*

Style/Documentation:
  Enabled: false
