AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - config/environments/**/*
    - config/initializers/**/*
    - db/schema.rb
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/import/**/*

Style/Documentation:
  Enabled: false
