require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - bin/**/*
    - config/{environments,initializers}/**/*
    - config/{application,boot,environment,puma,spring}.rb
    - db/schema.rb
    - db/migrate/*.rb
    - config.ru
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - lib/tasks/import/**/*
    - spec/**/*

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
