AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - config/environments/**/*
    - config/initializers/**/*
    - db/schema.rb
    - db/migrate/*.rb

Style/Documentation:
  Enabled: false
