# frozen_string_literal: true

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'simplecov'

SimpleCov.start do
  refuse_coverage_drop
end
# frozen_string_literal: true

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  config.shared_context_metadata_behavior = :apply_to_host_groups
end

def when_current_user_is(user, options = {})
  current_user = 
    case user
    when Symbol then create :user, user 
    when User then user 
    when nil then nil
    else raise ArgumentError, 'Invalid user type'
    end
    set_current_user current_user, options
end

def set_current_user(user, **options)
  if options.key? :view
    assign :current_user, user
  elsif options.key? :integration
    page.set_rack_session(user_id: user.id)
  elsif user.present?
    session[:user_id] = user.id
  else session[:spire] = build(:user).spire
  end
end
