# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Passenger.create(name: 'James Johnson',
                address: '4553 Norma Lane',
                email: 'johnson@gmail.com',
                phone: '318-621-8938',
                wheelchair: false ,
                active: true,
                permanent: false,
                expiration: '7/14/2017',
                note: '')
Passenger.create(name: 'Brenda Lima Cavalcanti',
                address: '4992 Chandler Drive',
                email: 'brenda@gmx.com',
                phone: '417-579-3039',
                wheelchair: true,
                active: false,
                permanent: false,
                expiration: '6/14/2017',
                note: '')
Passenger.create(name: 'Eleni Stegink',
                address: '2360 Ethels Lane',
                email: 'Stegink@armyspy.com ',
                phone: '863-709-1728',
                wheelchair: false,
                active: true,
                permanent: true,
                expiration: 'None',
                note: '')
Passenger.create(name: 'Chu Hưng Bông',
                address: '2537 Seltice Way',
                email: 'ChuHungBong@jourrapide.com ',
                phone: '208-732-7542',
                wheelchair: false,
                active: true,
                permanent: false,
                expiration: '8/22/2017',
                note: '')
Passenger.create(name: 'Gilly Galbassi',
                address: '1649 Trainer Avenue',
                email: 'Gilly@teleworm.us ',
                phone: '309-528-1703',
                wheelchair: true,
                active: true,
                permanent: false,
                expiration: '6/30/2017',
                note: '')
Passenger.create(name: 'Shu Hê',
                address: '1880 Beechwood Drive',
                email: 'ShuHe@jourrapide.com ',
                phone: '412-200-6665',
                wheelchair: false,
                active: true,
                permanent: true,
                expiration: 'None',
                note: '')
Passenger.create(name: 'Carita Himanen',
                address: '4078 Charla Lane',
                email: 'Carita@teleworm.us ',
                phone: '972-750-1737',
                wheelchair: false,
                active: true,
                permanent: false,
                expiration: '8/1/2017',
                note: '')
Passenger.create(name: 'Sylvester Tejada Morales',
                address: '1918 West Side Avenue',
                email: 'Morales@jourrapide.com',
                phone: '201-242-3042' ,
                wheelchair: true,
                active: false,
                permanent: false,
                expiration: '6/10/2017',
                note: '')
Passenger.create(name: 'Hamano Abe',
                address: '408 Davis Lane',
                email: 'HamanoAbe@dayrep.com',
                phone: '720-294-4565' ,
                wheelchair: true,
                active: true,
                permanent: false,
                expiration: '8/12/2017',
                note: '')
Passenger.create(name: 'Henrik Jørgensen',
                address: '4340 Cardinal Lane',
                email: 'Henrik@jourrapide.com',
                phone: '216-977-6176' ,
                wheelchair: true,
                active: false,
                permanent: false,
                expiration: '6/12/2017',
                note: '')
Passenger.create(name: 'Inayah Nashida Atiyeh',
                address: '4102 Lunetta Street',
                email: 'Inayah@armyspy.com',
                phone: '940-923-6307' ,
                wheelchair: true,
                active: true,
                permanent: true,
                expiration: 'None',
                note: '')
Passenger.create(name: 'Stella Sly',
                address: '3067 Zimmerman Lane',
                email: 'Sly@dayrep.com ',
                phone: '213-397-4797' ,
                wheelchair: false,
                active: true,
                permanent: false,
                expiration: '8/12/2017',
                note: '')
Passenger.create(name: 'Chinwemma Yobachi',
                address: '849 Pine Street',
                email: 'Yobachi@rhyta.com ',
                phone: '724-240-2537' ,
                wheelchair: true,
                active: true,
                permanent: true,
                expiration: 'None',
                note: '')
Passenger.create(name: 'Folke Dahl',
                address: '359 Ella Street',
                email: '650-229-6636',
                phone: 'FolkeDahl@teleworm.us' ,
                wheelchair: true,
                active: true,
                permanent: false,
                expiration: '7/11/2017',
                note: '')
Passenger.create(name: 'Vsevolod Artemiev',
                address: '4742 Pine Tree Lane',
                email: 'Artemiev@rhyta.com',
                phone: '240-414-4529',
                wheelchair: true,
                active: true,
                permanent: true,
                expiration: 'None',
                note: '')
Passenger.create(name: 'Temshe Saare',
                address: '455 Losh Lane',
                email: 'Saare@jourrapide.com',
                phone: '412-735-4208' ,
                wheelchair: false,
                active: true,
                permanent: false,
                expiration: '7/25/2017',
                note: '')
